config/routes.rb
SavedPages::Application.routes.draw do
  resources :users, :only => [:new, :create, :show]
  
  resource :session, :only => [:new, :create, :destroy]
  
  resources :bookmarks, :only => [:new, :create, :edit, :update, :destroy, :show]
  get 'u', to: 'bookmarks#unread'
  get 'archive', to: 'bookmarks#archive'
  get 'liked', to: 'bookmarks#like'
  
  resources :favorites, :only => [:create]
  
  root :to => "root#root"
end

app/models/archive.rb
class Archive < ActiveRecord::Base
  attr_accessible :bookmark_id, :user_id
  validates :user_id, :bookmark_id, presence: true
  
  def is_archived?
    self.is_archived
  end
  
  belongs_to(
  :user,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  belongs_to(
  :bookmark,
  :class_name => "Bookmark",
  :foreign_key => :bookmark_id,
  :primary_key => :id
  )
  
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_accessible :summary, :title, :url, :user_id, :author, :is_favorited, :is_archived
  validates :title, :url, :user_id, presence: true
  paginates_per 13
  
  def is_favorited?
    self.is_favorited
  end
  
  def is_archived?
    self.is_archived
  end
  
  belongs_to(
  :user,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )  
  
end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :follower_id, :user_id
  validates :follower_id, :user_id, presence: true
  
  belongs_to(
  :user,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  belongs_to(
  :follower,
  :class_name => "User",
  :foreign_key => :follower_id,
  :primary_key => :id
  )
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password
  attr_reader :password
  validates :email, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 6 }, on: :create
  validates :password, presence: true, on: :create
  
  before_validation(on: :create) do
    self.reset_session_token if !self.session_token
  end
  
  before_create :set_bookmarklet_token
  
  has_many(
  :bookmarks,
  :class_name => "Bookmark",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  has_many(
  :friends,
  :class_name => "Friend",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  has_many(
  :followed_users,
  :class_name => "Friend",
  :foreign_key => :follower_id,
  :primary_key => :id
  )
  
  def liked_bookmarks
    self.bookmarks.where(is_favorited: true)
  end
  
  def archived_bookmarks
    self.bookmarks.where(is_archived: true)
  end
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end
  
  def set_bookmarklet_token
    self.bookmarklet_token = self.class.generate_token
  end
  
  def reset_session_token
    self.session_token = self.class.generate_token
  end
  
  def reset_session_token!
    self.session_token = self.class.generate_token
    self.save!
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(email, password)
    user = User.find_by_email(email)
    if user
      user.is_password?(password) ? user : nil
    end
  end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper
  
  # before_filter :cors_preflight_check
  # # after_filter :cors_set_access_control_headers
  # 
  # # For all responses in this controller, return the CORS access control headers.
  # 
  # def cors_set_access_control_headers
  #   headers['Access-Control-Allow-Origin'] = '*'
  #   headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  #   headers['Access-Control-Max-Age'] = "1728000"
  # end
  # 
  # # If this is a preflight OPTIONS request, then short-circuit the
  # # request, return only the necessary headers and return an empty
  # # text/plain.
  # 
  # def cors_preflight_check
  #   if request.method == :options
  #     headers['Access-Control-Allow-Origin'] = '*'
  #     headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
  #     headers['Access-Control-Allow-Headers'] = 'X-Requested-With, X-Prototype-Version'
  #     headers['Access-Control-Allow-Headers'] = "*"
  #     headers['Access-Control-Max-Age'] = '1728000'
  #     render :text => '', :content_type => 'text/plain'
  #   end
  # end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  layout "bookmarks"
  skip_before_filter :verify_authenticity_token, :only => [:create]
  
  def create
    @bookmark = Bookmark.new(params[:bookmark])
    @bookmark.user_id = current_user.id
    
    if @bookmark.save
      render :json => @bookmark
    else
      render :json => @bookmark.errors.full_messages, status: 422
    end
  end
  
  def show
    @bookmark = Bookmark.find(params[:id])
    render :json => @bookmark
  end
  
  def edit
    @bookmark = Bookmark.find(params[:id])
    render :edit
  end
  
  def update
    @bookmark = Bookmark.find(params[:id])
    
    if @bookmark.update_attributes(params[:bookmark])
      render :json => @bookmark
    else
      render :json => @bookmark.errors.full_messages, status: 422
    end
  end
  
  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    render :json => nil
  end
  
  def unread
    if params[:unread]
      @bookmarks = current_user.bookmarks.where(is_archived: false).order("created_at DESC").page(params[:page])
    elsif params[:liked]
      @bookmarks = current_user.liked_bookmarks.order("updated_at DESC").page(params[:page])
    else
      @bookmarks = current_user.archived_bookmarks.order("updated_at DESC").page(params[:page])
    end
 
    render :json => {
      :models => @bookmarks,
      :page => params[:page],
      :total_pages => @bookmarks.total_pages
    }
  end
  
  def archive
    @archived_bookmarks = current_user.archived_bookmarks.page(params[:page])
    render :json => {
     :models => @archived_bookmarks,
     :page => params[:page],
     :total_pages => @archived_bookmarks.total_pages
    }
  end
  
  def like
    @liked_bookmarks = current_user.liked_bookmarks.page(params[:page])
    render :json => {
     :models => @liked_bookmarks,
     :page => params[:page],
     :total_pages => @liked_bookmarks.total_pages
    }
  end
  
  private
  
  def require_logged_in!
    redirect_to root_url if !current_user
  end
  
end

app/controllers/root_controller.rb
class RootController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password] 
    )
    
    if user
      login_user!(user)
      redirect_to '#/u'
    else
      flash.now[:error] = "Invalid email/password combination"
      render :new
    end
  end
  
  def destroy
    logout_current_user!
    render :json => nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
    if @user.save
      login_user!(@user)
      redirect_to '#/u'
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    render :json => @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def logout_current_user!
    current_user.reset_session_token!
    session[:session_token] = nil
  end
  
  def login_user!(user)
    @current_user = user
    session[:session_token] = user.session_token
  end
  
  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookmarks/archive.html.erb
<ul>
  <% @archived_bookmarks.each do |archived_bookmark| %>
  <li>
    <div class="archived">
      <p><%= archived_bookmark.title %></p>
    </div>
  </li>
  <% end %>
</ul>

app/views/bookmarks/edit.html.erb
<h3>Edit Article</h3>
<form action="<%= bookmark_url %>" method="post">
  <input type="hidden" 
         name="_method" 
        value="put">
  <input type="hidden" 
         name="authenticity_token" 
        value="<%= form_authenticity_token %>">
  
  <label for="bookmark_url">URL:</label>
  <input type="text" name="bookmark[url]" value="<%= @bookmark.url %>" id="bookmark_url">
  <br>
  
  <label for="bookmark_title">Title:</label>
  <input type="text" name="bookmark[title]" value="<%= @bookmark.title %>" id="bookmark_title">
  <br>
  
  <label for="bookmark_summary">Summary:</label>
  <input type="text" name="bookmark[summary]" value="<%= @bookmark.summary %>" id="bookmark_summary">
  <br>
  
  <input type="submit" value="Save changes">
</form>

app/views/bookmarks/like.html.erb
<ul>
  <% @liked_bookmarks.each do |liked_bookmark| %>
  <li>
    <div class="liked">
      <p><%= liked_bookmark.title %></p>
    </div>
  </li>
  <% end %>
</ul>

app/views/bookmarks/new.html.erb
<h3>Create New Bookmark</h3>
<form action="<%= bookmarks_url %>" method="post">
  <input type="hidden" 
         name="authenticity_token" 
        value="<%= form_authenticity_token %>">
  
  <label for="bookmark_url">URL</label>
  <input type="text" name="bookmark[url]" id="bookmark_url">
  <br>
  
  <label for="bookmark_title">Title</label>
  <input type="text" name="bookmark[title]" id="bookmark_title">
  <br>
  
  <label for="bookmark_summary">Summary</label>
  <input type="text" name="bookmark[summary]" id="bookmark_summary">
  <br>
  
  <label for="bookmark_author">Author</label>
  <input type="text" name="bookmark[author]" id="bookmark_author">
  <br>
  
  <input type="submit" value="Create bookmark">
</form>

app/views/bookmarks/unread.html.erb
<%= content_for :javascript do %>
  <%= javascript_tag do %>
    SavedPages.initialize({ bookmarks: <%= current_user.bookmarks.to_json %> });
  <% end %>
<% end %>  

<script>
$(document).ready(function() {
  $(".options").hide();
  $(".bookmark_row:last").css("border-bottom", "solid 1px #CFD1D1");
  
  if ($(".bookmark_row").length == 0) {
    $(".page_type").css("border-bottom", "1px solid #CFD1D1");
  }
  
  $.each($("a[data-favorited='true']"), function(index, value) {
    $(value).children('span').eq(0).addClass("heartToggle");
  })
});
</script>

<div class="page_type">Unread</div>
  <% if @bookmarks.length == 0  %>
    <div id="empty_list">No articles saved.</div>
  <% end %>
  <% @bookmarks.each do |bookmark| %>
  <div class="bookmark_row row">
      <div class="bookmark col-md-9" data-bookmark-id=<%= bookmark.id %>>
        <a href=<%= bookmark.url %>><span class="clickable_bookmark"><%= bookmark.title %></span></a>
      </div>
      <div class="options bookmark col-md-3">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-2 col-md-offset-1">
              <a href="#/bookmarks/<%= bookmark.id %>/edit" class="glyphicon_link"><span class="glyphicon glyphicon-pencil"></span></a>
            </div>
            <div class="col-md-2">
              <a href="#/u" class="like_bookmark glyphicon_link" data-favorited=<%= bookmark.is_favorited %> data-bookmark-id=<%= bookmark.id %>><span class="glyphicon glyphicon-heart"></span></a>
            </div>  
            <div class="col-md-2">
              <a href="#/u" class="archive_bookmark glyphicon_link" data-bookmark-id=<%= bookmark.id %>><span class="glyphicon glyphicon-inbox"></span></a>
            </div>  
            <div class="col-md-2">
              <a href="#/u" class="delete_bookmark glyphicon_link" data-bookmark-id=<%= bookmark.id %>><span class="glyphicon glyphicon-trash"></span></a>
            </div>
            <div class="col-md-2">
              <a href="#/u" class="share_bookmark glyphicon_link" data-bookmark-id=<%= bookmark.id %>><span class="glyphicon glyphicon-share"></span>
            </div>
          </div>
        </div>
      </div>
  </div>
  <% end %>
</div>

app/views/layouts/_errors.html.erb
<% if flash.now[:error] %>
  <% if flash.now[:error].is_a?(String) %>
    <div class="alert alert-danger">
      <%= flash.now[:error] %>
    </div>
  <% elsif flash.now[:error].is_a?(Array) %>
    <% flash.now[:error].each do |error| %>
       <div class="alert alert-danger">
         <%= error %>
        </div>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>SavedPages</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="application/json" id="bootstrapped_user_json">
    { "current_user": <%= current_user.to_json.html_safe %> }
  </script>
</head>
<body>
  <div class="container-fluid">
    <div class="row-fluid">
    
      <div id="sidebar" class="col-md-2"></div>
      <div id="content" class="col-md-10">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/bookmarks.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SavedPages</title>
  <%= stylesheet_link_tag    "bookmarks", :media => "all" %>
  <%= javascript_include_tag "bookmarks" %>
  <%= csrf_meta_tags %>

  $(document).ready(function(){
    SavedPages.initialize();
  });
</head>
<body>

  <% if current_user %>
  <%= current_user.email %>
  <% end %>
  
  <div id="sidebar">
    <h3>Your Articles</h3>
    <ul>
      <li><a href="#/u">Unread</a></li>
      <li><a href="#/liked">Liked</a></li>
      <li><a href="#/archive">Archive</a></li>
    </ul>
    <br>
    <h3>Discover</h3>
    <ul>
      <li>How to Save</li>
    </ul>
  </div>
  <div id="content">
  </div>

</body>
</html>

app/views/root/root.html.erb
<script>
$(document).ready(function() {
  $("#sidebar").hide();
  $("#content").removeClass("col-md-10");
  
  $("#sign_in_demo_btn").click(function(event) {
    event.preventDefault();
    $("#demo_form").submit();
  });
});


</script>

<nav class="navbar navbar-default" role="navigation">
  <div class="row" id="navbar_row">
    <div class="col-md-7">
      <img id="icon" src="assets/newspaper_icon.jpg"></img>
      <h2 id="root_header">SavedPages</h2>
    </div>
    <div class="col-md-5 account">
      <a data-toggle="modal" href="#create_user_modal" id="create_acct">Create Account</a>
      <a data-toggle="modal" href="#sign_in_modal">Sign In</a>
    </div>
</nav>





<!-- Create User Modal -->
<div class="modal fade" id="create_user_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Create An Account</h4>
      </div>
      <div class="modal-body">
        <form action="<%= users_url %>" method="post" class="root_form form-horizontal">
          <input type="hidden" 
                 name="authenticity_token"
                value="<%= form_authenticity_token %>">
          <label for="user_email" class="email_label">Email:</label>
          <input type="text" name="user[email]" id="user_email">
          <br>
          <label for="user_password">Password:</label>
          <input type="password" name="user[password]" id="user_password">
          <br>
          <input type="submit" value="Create Account" class="btn btn-primary">
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<!-- Sign In Modal -->
<div class="modal fade" id="sign_in_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Sign In</h4>
      </div>
      <div class="modal-body">
        <form action="<%= session_url %>" method="post" class="root_form form-horizontal">
          <input type="hidden" 
                 name="authenticity_token"
                 value="<%= form_authenticity_token %>">
          <label for="user_email" class="email_label">Email:</label>
          <input type="text" name="user[email]" id="user_email">
          <br>
          
          <label for="user_password">Password:</label>
          <input type="password" name="user[password]" id="user_password">
          <br>
          
          <input type="submit" value="Sign In" class="btn btn-primary">
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!-- Demo Account Form -->
<form id="demo_form" action="<%= session_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="password" name="user[email]" value="hire@me.com">
  <input type="password" name="user[password]" value="password">
  <input type="submit" value="Sign in">
</form>


<section id="root_main">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="assets/laptop.jpg"></img>
      </div>
      <div class="col-md-6" id="root_main_right">
        <h3>
          A simple tool for saving web pages 
          to read later on any computer or mobile device.
        </h3>
        <a data-toggle="modal" class="btn btn-danger btn-lg" href="#create_user_modal">Create an Account</a>
        <a class="btn btn-danger btn-lg" id="sign_in_demo_btn" href="#demo_form">Sign in with Demo</a>
      </div>
    </div>
  </div>
</section>

<section id="root_tutorial">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h2>How it Works</h3>
          <div>
            <span class="glyphicon glyphicon-bookmark root"></span>
            <h3>Add the Bookmarklet</h3>
            <p>Install the SavedPages bookmarklet by dragging it to your bookmark bar.</p>
          </div>
        </div>
        <div class="col-md-4 inner">
          <div>
            <span class="glyphicon glyphicon-list-alt root"></span>
            <h3>Save Articles for Later</h3>
            <p>When you find something you want to read, but you don't have the time, click the bookmarklet.</p>
          </div>
        </div>
        <div class="col-md-4 inner">
          <div>
            <span class="glyphicon glyphicon-briefcase root"></span>
            <h3>Read Anywhere</h3>
            <p>Return to the article later by signing in to your account.</p>
          </div>
        </div>
      </div>
    </div>
</section>
<div class="root_footer">
  <div class="container">
    <span>&copy; SavedPages, Benjamin Lee 2013</span>
  </div>
</div>

app/views/users/new.html.erb
<script>
$(document).ready(function() {
  $("#sidebar").hide();
  $("#content").removeClass("col-md-10");
});
</script>
<nav class="navbar navbar-default" role="navigation">
  <div class="row" id="navbar_row">
    <div class="col-md-7">
      <img id="icon" src="/assets/newspaper_icon.jpg"></img>
      <h2 id="root_header">SavedPages</h2>
    </div>
    <div class="col-md-5 account">
      <%= link_to("Create Account", new_user_url, id: "create_acct") %>
      <%= link_to("Sign In", new_session_url) %>
    </div>
</nav>

<div class="whole_container">
<div class="container">
  <%= render :partial => "layouts/errors" %>
  <header>
    <h3 id="error_create_account">Create Account</h3>
  </header>
  
  <section>
    <form action="<%= users_url %>" method="post" class="root_form form-horizontal">
      <input type="hidden" 
             name="authenticity_token"
             value="<%= form_authenticity_token %>">
      <label for="user_email" class="email_label">Email:</label>
      <input type="text" name="user[email]" id="user_email">
      <br>
      
      <label for="user_password">Password:</label>
      <input type="password" name="user[password]" id="user_password">
      <br>
      
      <input type="submit" value="Create Account" class="btn btn-primary">
    </form>
  </section>
</div>
</div>
<div class="footer">
  <div class="container">
    <span>&copy; SavedPages, Benjamin Lee 2013</span>
  </div>
</div>

app/views/users/show.html.erb
<div id="sidebar">
  <h3>Your Articles</h3>
  <ul>
    <li>Unread</li>
    <li>Liked</li>
    <li>Archive</li>
  </ul>
  <br>
  <h3>Discover</h3>
  <ul>
    <li>How to Save</li>
  </ul>
</div>

<div id="content">
  <ul>
    <li><p>Unread</p></li>
    <% @bookmarks.each do |bookmark| %>
    <li>
      <div class="bookmark" data-bookmark-id="<%= bookmark.id %>">
        <p><%= bookmark.title %></p>
        <%= link_to("Edit", edit_bookmark_url(bookmark.id), :method => :get) %>
        <%= link_to("Delete", bookmark_url(bookmark.id), :method => :delete) %>
      </div>
    </li>
    <% end %>
  </ul>
</div>